[tool.poetry]
name = "spark_delta_pro"
version = "0.1.0"
description = ""
authors = ["Tushar Pokle <tushar.pokle@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyspark = "^3.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
